### ISSUE TITLE
Add some options for the i18n feature

### ISSUE THREAD

**Issue by Baptistemontan** [Synphonyte/leptos-struct-table-macro#7]
Currently the `i18n` feature expect the `i18n` module to be at the crate root, and also expect the translation key to be the column name. This works in most cases for the `i18n` module but for the key it totally breaks when using namespaces and constrain the user to a specific path.

This issue propose the introduction of a struct attribute `#[i18n(path = path::to::i18n)]` to give the path to the `i18n` module, defaulted to `crate::i18n` when not set, and a field attribute `#[i18n(title_key = path.to.translation)]`to give the path to the translation for the `t!` macro, defaulted to the name of the column.

**Comment by Baptistemontan** [comment]
I just started working in this, but there are still small things that bother me and want your opinion @maccesch.

The feature is all or nothing, there is no way to opt out when enabled, so I would like to also propose a `#[i18n(disable)]` for fields (or struct?) to get back to the "normal" behavior, not sure about the argument name too, maybe `#[i18n(false)]` ?

**Comment by maccesch** [comment]
makes sense!

Let's do `#[i18n(skip)]` to be consistent.

**Comment by Baptistemontan** [comment]
Perfect!

**Comment by Baptistemontan** [comment]
It's been about an hour that I've been looking into `darling` docs, to the point I had to look at the macros source code and it seams they deal with multiple attrs by just considering them equivalent, so there is no way to differenciate beetween `#[i18n(skip)]` and `#[table(skip)]`. Leaving `darling` just for this feature would be completly stupid so the most suitable solution would be to just use `#[table]` instead of `#[i18n]` and just use a `i18n_` prefix: `#[table(i18n_path = path::to::i18n)]`, `#[table(i18n_key = path.to.translation)]`, `#[table(i18n_skip)]`

**Comment by maccesch** [comment]
hm ok. maybe nested like this?

```
#[table(i18n(skip))]
#[table(i18n(path = path::to::i18n))]
```

**Comment by Baptistemontan** [comment]
I haven't though of this, I can look into it yes
